import { StyleSheet } from "react-native";
import { COLORS } from "../../Colors";

export const styles = StyleSheet.create({
    safeContainer: {
      flex: 1,
      backgroundColor: COLORS.white,
    },
    container: {
      flexGrow: 1,
      paddingBottom: 24,
      backgroundColor: COLORS.white,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 24,
      paddingHorizontal: 16,
      paddingTop: 8,
      marginTop:10
    },
    userAvatar: {
      marginRight: 16,
      backgroundColor: COLORS.secondary,
      borderWidth: 2,
      borderColor: COLORS.primary,
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 2,
    },
    greeting: {
      fontSize: 22,
      fontWeight: '700',
      color: COLORS.textPrimary,
      marginBottom: 4,
    },
    caloriesContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    subGreeting: {
      fontSize: 14,
      color: COLORS.textSecondary,
      fontWeight: '500',
    },
    calendar: {
      borderRadius: 16,
      marginBottom: 24,
      elevation: 4,
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      overflow: 'visible',
    },
    searchContainer: {
      marginBottom: 24,
      paddingHorizontal: 8,
    },
    searchInput: {
      backgroundColor: COLORS.white,
      fontSize: 16,
    },
    card: {
      borderRadius:20,
      borderTopRightRadius:90,
      padding: 18,
      marginBottom: 10,
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      margin:3
    },
    nutritionItem: {
      width: '48%',
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      alignItems: 'center',
      gap: 8,
    },
    additionalInfo: {
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      borderRadius: 16,
      padding: 16,
      marginTop: 16,
    },
    errorContainer: {
      backgroundColor: '#FFEBEE',
      padding: 24,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
      gap: 16,
      borderWidth: 1,
      borderColor: '#FFCDD2',
    },
    errorText: {
      color: '#D32F2F',
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
      lineHeight: 24,
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 40,
      paddingHorizontal: 20,
      marginTop: 20,
    },
    emptyImage: {
      width: 240,
      height: 180,
      opacity: 0.8,
      marginBottom: 24,
    },
    emptyText: {
      fontSize: 20,
      fontWeight: '600',
      color: COLORS.textPrimary,
      textAlign: 'center',
      lineHeight: 28,
      marginBottom: 8,
    },
    emptySubtext: {
      fontSize: 16,
      fontWeight: '400',
      color: COLORS.textSecondary,
      textAlign: 'center',
      lineHeight: 24,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 40,
      backgroundColor: COLORS.white,
      borderRadius: 16,
      marginVertical: 16,
    },
    loadingText: {
      fontSize: 16,
      color: COLORS.textSecondary,
      fontWeight: '500',
      marginTop: 24,
      letterSpacing: 0.5,
    },
    infoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    },
    infoLabel: {
      color: COLORS.white,
      fontSize: 14,
      fontWeight: '500',
      flex: 1,
    },
    infoValue: {
      color: COLORS.white,
      fontSize: 14,
      fontWeight: '700',
      marginLeft: 16,
    },
    nutritionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 16,
    },
    itemLabel: {
      color: COLORS.white,
      fontSize: 14,
      fontWeight: '500',
      marginTop: 8,
    },
    itemValue: {
      color: COLORS.white,
      fontSize: 18,
      fontWeight: '700',
      marginTop: 4,
    },
    servingChip: {
      alignSelf: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.9)',
      paddingVertical: 6,
    },
    servingText: {
      color: COLORS.primary,
      fontSize: 14,
      fontWeight: '600',
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
      paddingHorizontal: 8,
    },
    cardTitle: {
      color: COLORS.white,
      fontSize: 20,
      fontWeight: '700',
      marginLeft: 12,
      letterSpacing: 0.5,
    },
    text:{
      fontSize:18,
      fontWeight:'700',
      color:'#333',
      marginLeft:10,
      marginTop:5
    }
  });